export { FunctionSpaceContext } from './context.js';
export type { FSContext } from './context.js';
export { FunctionSpaceProvider, resolveTheme } from './FunctionSpaceProvider.js';
export type { FunctionSpaceProviderProps, FSThemeInput, FSTheme, ResolvedFSTheme } from './FunctionSpaceProvider.js';
export { FS_DARK, FS_LIGHT, NATIVE_DARK, NATIVE_LIGHT, THEME_PRESETS } from './themes.js';
export type { ThemePresetId, ChartColors, FanBandColors } from './themes.js';
export { resolveChartColors, getPresetChartColors } from './themes.js';
export { useMarket } from './useMarket.js';
export { useConsensus } from './useConsensus.js';
export { usePositions } from './usePositions.js';
export { useTradeHistory } from './useTradeHistory.js';
export { useBucketDistribution } from './useBucketDistribution.js';
export { useMarketHistory } from './useMarketHistory.js';
export { useDistributionState } from './useDistributionState.js';
export type { DistributionState, DistributionStateConfig } from './useDistributionState.js';
export { useAuth } from './useAuth.js';
export type { PasswordlessLoginResult } from '@functionspace/core';
export { useCustomShape } from './useCustomShape.js';
export type { UseCustomShapeReturn } from './useCustomShape.js';
export { useChartZoom } from './useChartZoom.js';
export type { ChartZoomOptions, ChartZoomResult } from './useChartZoom.js';
export { rechartsPlotArea } from './rechartsHelpers.js';

