#!/usr/bin/env node
/**
 * Reads indexspace/.env (single source of truth) and syncs:
 *   - Non-NEXT_PUBLIC_ vars  →  indexspace/backend/.env
 *   - NEXT_PUBLIC_* vars     →  indexspace/ui/.env.local
 *
 * Run via: bun sync-env  (or node scripts/sync-env.mjs)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, 'indexspace', '.env');
const backendEnvPath = resolve(root, 'indexspace', 'backend', '.env');
const uiEnvPath = resolve(root, 'indexspace', 'ui', '.env.local');
const contractsEnvPath = resolve(root, 'indexspace', 'contracts', '.env');

if (!existsSync(envPath)) {
  console.error(`sync-env: ${envPath} not found`);
  console.error(`  Copy indexspace/.env.example to indexspace/.env and fill in values.`);
  process.exit(1);
}

const lines = readFileSync(envPath, 'utf8').split('\n');

// Only real KEY=VALUE lines — strip comments and blanks
const varLines = lines.filter((l) => {
  const t = l.trim();
  return t.length > 0 && !t.startsWith('#') && t.includes('=');
});

const backendLines = varLines.filter((l) => !l.trimStart().startsWith('NEXT_PUBLIC_'));
const uiLines = varLines.filter((l) => l.trimStart().startsWith('NEXT_PUBLIC_'));

const header = '# Auto-generated by scripts/sync-env.mjs from indexspace/.env — do not edit manually\n';

writeFileSync(backendEnvPath, header + backendLines.join('\n') + '\n');
console.log(`sync-env: wrote ${backendLines.length} backend var(s) to indexspace/backend/.env`);
backendLines.forEach((l) => {
  const key = l.split('=')[0] ?? '';
  const redact = key.includes('KEY') || key.includes('PASSWORD') || key.includes('SECRET') || key.includes('TOKEN');
  console.log(`  ${redact ? `${key}=***` : l}`);
});

writeFileSync(contractsEnvPath, header + backendLines.join('\n') + '\n');
console.log(`\nsync-env: wrote ${backendLines.length} contracts var(s) to indexspace/contracts/.env`);
backendLines.forEach((l) => {
  const key = l.split('=')[0] ?? '';
  const redact = key.includes('KEY') || key.includes('PASSWORD') || key.includes('SECRET') || key.includes('TOKEN');
  console.log(`  ${redact ? `${key}=***` : l}`);
});

writeFileSync(uiEnvPath, header + uiLines.join('\n') + '\n');
console.log(`\nsync-env: wrote ${uiLines.length} UI var(s) to indexspace/ui/.env.local`);
uiLines.forEach((l) => console.log(`  ${l}`));
