#!/usr/bin/env node
/**
 * Reads indexspace/.env and writes NEXT_PUBLIC_* vars to indexspace/ui/.env.local.
 * Run once before starting the dev server, or wire into dev scripts.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, 'indexspace', '.env');
const outPath = resolve(root, 'indexspace', 'ui', '.env.local');

if (!existsSync(envPath)) {
  console.log(`sync-env: ${envPath} not found, skipping`);
  process.exit(0);
}

const lines = readFileSync(envPath, 'utf8').split('\n');
const nextPublicLines = lines.filter((l) => l.trimStart().startsWith('NEXT_PUBLIC_'));

if (nextPublicLines.length === 0) {
  console.log('sync-env: no NEXT_PUBLIC_* vars found in indexspace/.env');
  process.exit(0);
}

const header = '# Auto-generated by scripts/sync-env.mjs — do not edit manually\n';
writeFileSync(outPath, header + nextPublicLines.join('\n') + '\n');
console.log(`sync-env: wrote ${nextPublicLines.length} NEXT_PUBLIC_* var(s) to indexspace/ui/.env.local`);
nextPublicLines.forEach((l) => console.log(`  ${l}`));
